### ISSUE TITLE
Update the docker image

### ISSUE THREAD

**Issue by krahser** [optimized/docker-gatsbyjs#2]
It seems like the automated build at [docker hub](https://hub.docker.com/r/6e6a/docker-gatsbyjs/builds/) it's not working.

Could you check that please?

Thank you very much for this repo!

**Comment by noeljackson** [comment]
We changed URLs a while back and they don't reroute automatically. Sorry for this. Won't have any name changes in the future.

This is the new repository:
https://hub.docker.com/r/optimized/docker-gatsbyjs/
